In [4]:
# xy split

import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X

list(y)

[0, 1, 2, 3, 4]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

X_train



y_train

X_test


y_test

[1, 4]

In [6]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]

In [7]:
#normalize (numerical)


from sklearn import preprocessing
import numpy as np
x_array = np.array([2,3,5,6,7,4,8,7,6])
normalized_arr = preprocessing.normalize([x_array])
print(normalized_arr)

[[0.11785113 0.1767767  0.29462783 0.35355339 0.41247896 0.23570226
  0.47140452 0.41247896 0.35355339]]


In [8]:
# Normalize columns in a dataset using normalize

import pandas as pd
housing = pd.read_csv("/Users/edudarrelljockers/Downloads/Data_Marketing_Customer_Analysis_Round2_(6).csv")

In [14]:
from sklearn import preprocessing
x_array = np.array(housing['Income'])
normalized_arr = preprocessing.normalize([x_array])
print(normalized_arr)

[[0.00952489 0.         0.00439051 ... 0.00790029 0.01273086 0.        ]]


In [ ]:
# Using MinMaxScaler() to Normalize Data in Python

from sklearn import preprocessing
import pandas as pd
housing = pd.read_csv("/Users/edudarrelljockers/Downloads/Data_Marketing_Customer_Analysis_Round2_(6).csv")
scaler = preprocessing.MinMaxScaler()
names = Income.columns
d = scaler.fit_transform(housing)
scaled_df = pd.DataFrame(d, columns=names)
scaled_df.head()

In [17]:

# example of a one hot encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
